INSERT INTO public.item_types(name) VALUES ('Adventuring gear');
INSERT INTO public.item_types(name) VALUES ('Ammo');
INSERT INTO public.item_types(name) VALUES ('Armor');
INSERT INTO public.item_types(name) VALUES ('Light Armor');
INSERT INTO public.item_types(name) VALUES ('Medium Armor');
INSERT INTO public.item_types(name) VALUES ('Heavy Armor');
INSERT INTO public.item_types(name) VALUES ('Artifact');
INSERT INTO public.item_types(name) VALUES ('Clothes');
INSERT INTO public.item_types(name) VALUES ('Component');
INSERT INTO public.item_types(name) VALUES ('Equipment');
INSERT INTO public.item_types(name) VALUES ('Material');
INSERT INTO public.item_types(name) VALUES ('Mount');
INSERT INTO public.item_types(name) VALUES ('Musical Instrument');
INSERT INTO public.item_types(name) VALUES ('Potion');
INSERT INTO public.item_types(name) VALUES ('Relic');
INSERT INTO public.item_types(name) VALUES ('Ring');
INSERT INTO public.item_types(name) VALUES ('Rod');
INSERT INTO public.item_types(name) VALUES ('Scroll');
INSERT INTO public.item_types(name) VALUES ('Shield');
INSERT INTO public.item_types(name) VALUES ('Staff');
INSERT INTO public.item_types(name) VALUES ('Tool');
INSERT INTO public.item_types(name) VALUES ('Vehicle');
INSERT INTO public.item_types(name) VALUES ('Wand');
INSERT INTO public.item_types(name) VALUES ('Wondrous Item');
