INSERT INTO public.weapon_types(name, description) VALUES ('Club', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Dagger', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Greatclub', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Handaxe', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Javelin', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Light', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Mace', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Quarterstaff', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Sickle', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Spear', 'Simple melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Light Crossbow', 'Simple ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Dart', 'Simple ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Shortbow', 'Simple ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Sling', 'Simple ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Battleaxe', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Flail', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Glaive', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Greataxe', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Greatsword', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Halberd', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Lance', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Longsword', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Maul', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Morningstar', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Pike', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Rapier', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Scimitar', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Shortsword', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Trident', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('War', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Warhammer', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Whip', 'Martial melee weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Blowgun', 'Martial ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Hand Crossbow', 'Martial ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Heavy Crossbow', 'Martial ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Longbow', 'Martial ranged weapon');
INSERT INTO public.weapon_types(name, description) VALUES ('Net', 'Martial ranged weapon');